### ISSUE TITLE
Corrupt writing?

### ISSUE THREAD

**Issue by JohnEmhoff** [pluralsight/spavro#9]
I'm sorry to come here with such a vague issue, but in cases where I have more than just a couple thousand rows spavro is generating enormous files with lots of garbage on the end. A hex dump of the file seems to show this garbage looks a lot like data earlier in the file.

Here's a script that will reproduce: https://gist.github.com/JohnEmhoff/b60f27a1a455c866d398b1d9fff653d0

It will generate 100k rows of where each row has two strings and a number. The file it generates (out.avro) is 57GB on my machine, where I would expect it to be around a megabyte or so. I hope I'm just using the library egregiously incorrectly? This is on spavro 1.1.22.

**Comment by JohnEmhoff** [comment]
Hmmm, I think I found the issue. After flushing the buffer, it's cleared with `.truncate()`:

https://github.com/pluralsight/spavro/blob/master/src/spavro/datafile.py#L211

Per the [docs](https://docs.python.org/3/library/io.html#io.IOBase.truncate), this will reset the buffer to size zero, but will not move the current offset -- this can be easily seen by running `self.buffer_writer.ftell()`, which will return a number higher than the sync interval. I assume what's happening is that the next time data is written to the buffer, the space up until this point will get zero-filled or something along those lines?

Anywhoo, adding a `self.buffer_writer.seek(0)` after the `.truncate()` seems to completely fix everything. I'll put together a PR if you like?

**Comment by tenth10th** [comment]
(resolved in https://github.com/pluralsight/spavro/pull/10 )
